#! /bin/bash

SCRIPTS=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
ROOT=$(dirname $SCRIPTS)

export REACT_PACKAGER_LOG="$ROOT/server.log"

cd $ROOT

function cleanup {
    kill 0
}
trap cleanup EXIT

./node_modules/react-native/packager/packager.sh --nonPersistent &

xctool \
  -project ios/RNIntegrationTestExample.xcodeproj \
  -scheme RNIntegrationTestExample -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 5,OS=9.3' \
  test